# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MissF' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for MissF

    pod 'AFNetworking', '~> 3.1.0'
    pod 'SDWebImage', '~> 3.8.1'
    pod 'MJExtension', '~> 3.0.13'
    pod 'Reachability', '~> 3.2'
    pod 'MJRefresh', '~> 3.1.12'
    pod 'SDAutoLayout', '~> 2.1.4'
    pod 'SDCycleScrollView', '~> 1.65'
    #pod 'ReactiveCocoa', ‘2.5’
    pod 'Masonry', '~> 1.0.2'
    pod 'IQKeyboardManager', '~> 4.0.10'
    pod 'MBProgressHUD', '1.0.0'
    pod 'SVProgressHUD', :git => 'https://github.com/SVProgressHUD/SVProgressHUD.git'#先集成在删除切换
    pod 'TTTAttributedLabel', '~> 2.0.0' #富文本编辑
    #pod 'RegexKitLite-NoWarning', '1.1.0'#正则表达式
    pod 'SDCAlertView','~>2.5.2' #提示窗
    #pod 'TMCache', '2.1.0'#缓存
    pod 'iVersion', '1.11.5'#版本检查更新
    pod 'SSKeychain', '1.4.1'
    pod 'iCarousel', '~> 1.8.3'
    pod 'FDFullscreenPopGesture', '1.1'#全局侧滑
    pod 'CYLTabBarController', '~> 1.13.1'
    pod 'DZNEmptyDataSet', '~> 1.8.1'
    pod 'FMDB', '~> 2.7.2'
    pod 'MLeaksFinder', '~> 0.2.1'
    pod 'YTKKeyValueStore', '~> 0.1.2'#本地网络数据缓存
    pod 'TTGTagCollectionView' #标签按钮


  target 'MissFTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'MissFUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
